name: Deploy to Railway
on:
    push:
        branches: [master]

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout Repo
              uses: actions/checkout@v3

            - name: Setup Node
              uses: actions/setup-node@v3
              with:
                  node-version: 16.x

            - name: Install dependencies
              run: yarn install --frozen-lockfile

            - name: Install Railway
              run: npm i -g @railway/cli

            - run: npm run setup

            - name: Apply all pending migrations to the database
              run: npx prisma migrate deploy
              env:
                  DATABASE_URL: ${{ secrets.DATABASE_URL }}

            - name: Deploy
              run: railway up
              env:
                  RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
